on: push
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    with:
      NOMAD_VAR_PORTS: '{ 80 = "http" }'
      PLATFORMS: linux/amd64,linux/arm64
